//! Generated by `scripts/import_lintian_parity.py`. Do not edit.
//!
//! Source-tree and Binary-package Parity recipes whose `eval/hints`
//! mention a catalogued LN Tag.

mod common;

use test_case::test_case;

const SOURCE_TREE_RECIPES: &[&str] = &[
    "checks/debian/rules/generic-empty",
    "checks/debian/rules/legacy-binary",
    "checks/debian/rules/legacy-etcfiles",
    "checks/debian/rules/rules-missing-targets",
    "checks/debian/rules/rules-missing-targets-with-known-includes",
    "checks/fields/required/generic-empty",
];

const BINARY_PACKAGE_RECIPES: &[&str] = &["checks/fields/required/fields-general-missing"];

#[test]
fn listed_source_tree_recipes_match_vendored_catalogued() {
    let listed: Vec<String> = SOURCE_TREE_RECIPES
        .iter()
        .map(|rel| (*rel).to_string())
        .collect();
    assert_eq!(common::catalogued_source_tree_recipe_rels(), listed);
}

#[test]
fn listed_binary_package_recipes_match_vendored_catalogued() {
    let listed: Vec<String> = BINARY_PACKAGE_RECIPES
        .iter()
        .map(|rel| (*rel).to_string())
        .collect();
    assert_eq!(common::catalogued_binary_package_recipe_rels(), listed);
}

#[test_case("checks/debian/rules/generic-empty"; "checks_debian_rules_generic_empty")]
#[test_case("checks/debian/rules/legacy-binary"; "checks_debian_rules_legacy_binary")]
#[test_case("checks/debian/rules/legacy-etcfiles"; "checks_debian_rules_legacy_etcfiles")]
#[test_case("checks/debian/rules/rules-missing-targets"; "checks_debian_rules_rules_missing_targets")]
#[test_case("checks/debian/rules/rules-missing-targets-with-known-includes"; "checks_debian_rules_rules_missing_targets_with_known_includes")]
#[test_case("checks/fields/required/generic-empty"; "checks_fields_required_generic_empty")]
fn lintian_parity_source_tree(recipe: &str) {
    common::assert_source_tree_parity(recipe);
}

#[test_case("checks/fields/required/fields-general-missing"; "checks_fields_required_fields_general_missing")]
fn lintian_parity_binary_package(recipe: &str) {
    common::assert_binary_package_parity(recipe);
}
